### ISSUE TITLE
Can not install the red pnda on  a vm without using ova

### ISSUE THREAD

**Issue by Gaurav-Pande** [pndaproject/red-pnda#26]
Followed the steps mentioned in : https://github.com/pndaproject/red-pnda/blob/develop/roll_your_own_RED_PNDA.md

but after couple of minutes there is a broken dependency of tornado in python ssl module whcih throws out from the installation.

Error trace:

Collecting tornado>=4.0 (from ipykernel->jupyter)
  Downloading https://files.pythonhosted.org/packages/45/ec/f2a03a0509bcfca336bef23a3dab0d07504893af34fd13064059ba4a0503/tornado-5.1.tar.gz (516kB)
    100% |################################| 522kB 39.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-IiNf2t/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-IiNf2t/tornado/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
jupyter.sh: line 16: jupyter: command not found

**Comment by 91pavan** [comment]
Hi Gaurav,

Can you try adding this line just before `pip install jupyter` line in jupyter.sh file?

    pip install tornado==4.*

Newer versions of tornado doesn’t seem to support python versions < 2.7.9.

You may need to start the whole installation again by launching a new VM.

Let me know how it goes.

PS: We’re in the process of dockering red-pnda so watch this space.

**Comment by Gaurav-Pande** [comment]
Hi,

No it does not resolve the issue.
May I know when will the installation support the tornado. As with the current method, I don't think we can install the red pnda.
